phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/PageCssBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apd.phoenix.shopping.view.jsf.bean;

import java.io.Serializable;
import java.util.Properties;
import javax.annotation.PostConstruct;
import javax.ejb.Stateful;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.component.UIInput;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import org.apache.commons.lang.StringUtils;
import com.apd.phoenix.core.StringEscape;
import com.apd.phoenix.core.utility.TenantConfigRepository;
import com.apd.phoenix.service.business.AccountBp;
import com.apd.phoenix.service.business.IpSubdomainRestriction;
import com.apd.phoenix.service.persistence.multitenancy.api.CurrentTenantDomain;
import com.apd.phoenix.service.persistence.multitenancy.impl.CurrentTenantIdentifierResolverImpl;

/**
 * This class is used by the ecommerceMainTemplate.xthml template page to get
 * the appropriate css file for a specific customer.
 * <br /><br />
 * To set a CSS file for a particular account, save the file in
 * phoenix-shopping/src/main/webapp/resources/css/main, then add a property to
 * cssMap.properties and cssMapResponsive.properties, from the root account name
 * to the path of the CSS file.
 *
 * @author RHC
 *
 */
@Named
@Stateful
@RequestScoped
public class PageCssBean implements Serializable {

    private static final long serialVersionUID = 1L;
    private static final String CUSTOM_CSS_URL_SUFFIX = "/phoenix-css/";
    private static final String SUBDOMAIN_IMAGES_SUFFIX = "/images/";
    private static final String SUBDOMAIN_WELCOME_IMAGES_SUFFIX = "welcome-images/";
    private static final String SUBDOMAIN_LOGOS_SUFFIX = "logos/";
    private static final String SUBDOMAIN_CSS_LOCATION = "css/subDomain/";
    private static final String CSS_FILE_EXTENSION = ".css";

    private Properties themeMapProperties;
    private Properties tenantProperties;

    private String staticContentURL;
    private String tenantName;

    @Inject
    private AccountBp accountBp;

    @Inject
    private CurrentTenantDomain currentTenantDomain;

    @PostConstruct
    public void init() {
        tenantName = TenantConfigRepository.getInstance().getTenantNameByDomain(currentTenantDomain.getDomain());
        if (tenantName == null) {
            tenantName = TenantConfigRepository.getInstance().getTenantNameById(
                    CurrentTenantIdentifierResolverImpl.getCurrentTenant());
        }

        staticContentURL = TenantConfigRepository.getInstance().getProperty(tenantName, "tenant",
                "content.service.secure.tenant.domain");
        themeMapProperties = TenantConfigRepository.getInstance().getPropertiesByTenantName(tenantName, "themeMap");
        tenantProperties = TenantConfigRepository.getInstance().getPropertiesByTenantName(tenantName, "tenant");
    }

    public String getSubDomainBasedCssFile() {
        String cssKey = getSubdomainValue();
        if (cssKey.isEmpty() || cssKey.equals(IpSubdomainRestriction.GENERIC_SUBDOMAIN)) {
            return "";
        }
        return staticContentURL + CUSTOM_CSS_URL_SUFFIX + SUBDOMAIN_CSS_LOCATION + StringEscape.escapeForUrl(cssKey)
                + CSS_FILE_EXTENSION;
    }

    public String getSubdomainValue() {
        HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext()
                .getRequest();
        return IpSubdomainRestriction.ipAndDomainInfo(request)[1];
    }

    public String getSubDomainWelcomeMessage() {
        return this.getSubdomainSpecificProperty("_WelcomMessage");
    }

    public String getSubDomainWelcomeMessageHeader() {
        return this.getSubdomainSpecificProperty("_WelcomMessageHeader");
    }

    public String getSubDomainWelcomeImage() {
        return staticContentURL + SUBDOMAIN_IMAGES_SUFFIX + SUBDOMAIN_WELCOME_IMAGES_SUFFIX
                + this.getSubdomainSpecificProperty("_WelcomeImage");
    }

    public String getSubDomainLogo() {
        String imageName = this.getSubdomainSpecificProperty("_Logo");
        if (StringUtils.isNotEmpty(imageName)) {
            return staticContentURL + SUBDOMAIN_IMAGES_SUFFIX + SUBDOMAIN_LOGOS_SUFFIX + imageName;
        }
        else {
            return "";
        }
    }

    public String getCustomerServiceInfo() {
        return this.getSubdomainSpecificProperty("_customerServiceInfo");
    }

    public String getCallUsPhone() {
        return this.getSubdomainSpecificProperty("_callUsPhone");
    }

    public String getCallUsDays() {
        return this.getSubdomainSpecificProperty("_callUsDays");
    }

    public String getCallUsHrs() {
        return this.getSubdomainSpecificProperty("_callUsHrs");
    }

    public String getEmailUsAddress() {
        return this.getSubdomainSpecificProperty("_emailUsAddress");
    }

    public String getVisitUsSite() {
        return this.getSubdomainSpecificProperty("_visitUsSite");
    }

    public String getVisitUsSiteToDisplay() {
        return this.getSubdomainSpecificProperty("_visitUsSiteToDsiplay");
    }

    public String getFaceBook() {
        return this.getSubdomainSpecificProperty("_facebook");
    }

    public String getLinkedIn() {
        return this.getSubdomainSpecificProperty("_linkedin");
    }

    public String getYouTube() {
        return this.getSubdomainSpecificProperty("_youtube");
    }

    public String getWordPress() {
        return this.getSubdomainSpecificProperty("_wordpress");
    }

    public String getCopyRight() {
        return this.getSubdomainSpecificProperty("_copyright");
    }

    public String getAboutUsUrl() {
        return this.getSubdomainSpecificProperty("_aboutUsUrl");
    }

    public String getContactUsUrl() {
        return this.getSubdomainSpecificProperty("_contactUsUrl");
    }

    public String getReturnPolicyUrl() {
        return this.getSubdomainSpecificProperty("_returnPolicyUrl");
    }

    public String getTermsOfUseUrl() {
        return this.getSubdomainSpecificProperty("_termsOfUseUrl");
    }

    public String getSecurityUrl() {
        return this.getSubdomainSpecificProperty("_securityUrl");
    }

    public String getPrivacyUrl() {
        return this.getSubdomainSpecificProperty("_privacyUrl");
    }

    public String getPrivacyEmail() {
        return tenantProperties.getProperty("privacy_page_email_address");
    }

    public String getCreateUserRequestInstructions() {
        return this.getSubdomainSpecificProperty("_createUserRequest_instructions");
    }

    public String getShowTrustKeeperPopup() {
        return this.getSubdomainSpecificProperty("_showTrustKeeperPopup");
    }

    /**
     * Takes a property name, and returns the value of that property for the 
     * subdomain and tenant. Follows this logic:
     * 
     * If the tenant is APD, checks <subdomain>_<property_value>, then 
     * <generic_subdomain>_<property_value>. If the tenant isn't APD, checks
     * <tenantName>_<subdomain>_<property_value>, then 
     * <tenantName>_<generic_subdomain>_<property_value>, then
     * <generic_subdomain>_<property_value>.
     * 
     * @param propertyName
     * @return
     */
    private String getSubdomainSpecificProperty(String propertyName) {
        //sets the tenant name prefix for the values to fetch
        String tenantPrefix = tenantName + "_";
        //if the tenant is APD, sets the prefix to the empty string
        if (TenantConfigRepository.getInstance().getGenericTenantId().equals(
                TenantConfigRepository.getInstance().getTenantIdByName(tenantName))) {
            tenantPrefix = "";
        }
        //used to look up the tenant's subdomain-specific styling
        String subdomainKey = tenantPrefix + this.getSubdomainValue() + propertyName;
        //used to look up the tenant's generic styling
        String tenantKey = tenantPrefix + IpSubdomainRestriction.GENERIC_SUBDOMAIN + propertyName;
        //used to look up the site's generic styling 
        String genericKey = IpSubdomainRestriction.GENERIC_SUBDOMAIN + propertyName;
        if (themeMapProperties.containsKey(subdomainKey)) {
            return themeMapProperties.getProperty(subdomainKey, "");
        }
        else if (themeMapProperties.containsKey(tenantKey)) {
            return themeMapProperties.getProperty(tenantKey, "");
        }
        else {
            return themeMapProperties.getProperty(genericKey, "");
        }
    }

    public void validateEmailDomain(FacesContext context, UIComponent component, Object value) {
        if (value != null && !accountBp.validEmailAddress(value.toString(), getSubdomainValue())) {
            ((UIInput) component).setValid(false);
            FacesMessage message = new FacesMessage();
            message.setSeverity(FacesMessage.SEVERITY_ERROR);
            message.setSummary(TenantConfigRepository.getInstance().getProperty(tenantName, "ecommerce",
                    "registration.email.invalid.summary"));
            message.setDetail(TenantConfigRepository.getInstance().getProperty(tenantName, "ecommerce",
                    "registration.email.invalid.detail"));
            context.addMessage(null, message);
        }
    }
}

phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/user/UserProfileBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apd.phoenix.shopping.view.jsf.bean.user;

import javax.ejb.Stateful;
import javax.enterprise.context.ConversationScoped;
import javax.inject.Named;

@Named
@Stateful
@ConversationScoped
public class UserProfileBean {

    private String firstName;
    private String lastName;

    public String getFirstName() {
        return "Welcome";
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return "User!!!";
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

}

phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/user/UserRegistrationBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apd.phoenix.shopping.view.jsf.bean.user;

import javax.ejb.Stateful;
import javax.enterprise.context.ConversationScoped;
import javax.inject.Inject;
import javax.inject.Named;
import com.apd.phoenix.service.business.SystemUserBp;
import com.apd.phoenix.service.model.SystemUser;

@Named
@Stateful
@ConversationScoped
public class UserRegistrationBean {

    private SystemUser user;

    @Inject
    private SystemUserBp systemUserBp;

    public void beginUserRegistration() {
        user.setLogin("New User");
        systemUserBp.beginUserRegistration(user);
    }

    public boolean isUsernameAvailable(String username) {
        return systemUserBp.isLoginAvailable(username);
    }

}

phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/utils/LinksBean.java
package com.apd.phoenix.shopping.view.jsf.bean.utils;

import java.io.Serializable;
import java.net.InetAddress;
import javax.ejb.Stateless;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Named;

/**
 * This is a utility bean, used to generate URLs for the shopping site.
 * 
 * @author RHC
 *
 */
@Named
@Stateless
public class LinksBean implements Serializable {

    private static final String ECOMMERCE_PRODUCT_LOOKAHEAD_ENDPOINT = "/rest/typeahead/mainSearch/";
    private static final String ECOMMERCE_CARTRIDGE_LOOKAHEAD_ENDPOINT = "/rest/typeahead/cartridgeSearch/";
    private static final String ECOMMERCE_MODEL_LOOKAHEAD_ENDPOINT = "/rest/typeahead/modelSearch/";
    private static final String ECOMMERCE_SMART_SEARCH_LOOKAHEAD = "/rest/typeahead/smartSearch/";
    private static final String ECOMMERCE_SMART_SEARCH_CARTRIDGE_NUMBER_LOOKAHEAD = "/rest/typeahead/smartSearch/cartridge/";
    private static final String ECOMMERCE_SMART_SEARCH_MODEL_NUMBER_LOOKAHEAD = "/rest/typeahead/smartSearch/model/";
    private static final String PUBLIC_RESET_PASSWORD_PAGE = "/ecommerce/user/resetPassword.xhtml";
    private static final String RESET_PASSWORD_PAGE = "/ecommerce/account/resetPassword.xhtml";
    public static final String PASSWORD_EXPIRED_PAGE = "/ecommerce/account/passwordExpired.xhtml";
    private static final String MY_ACCOUNT_PAGE = "/ecommerce/account/manage.xhtml";
    private static final String ECOMMERCE_HOME_PAGE = "/ecommerce/home.xhtml";
    private static final String ECOMMERCE_CASHOUT = "/ecommerce/cashout/checkout.xhtml";
    private static final String ECOMMERCE_PUNCHOUT = "/ecommerce/marketplace/returnCart.xhtml";
    private static final String ECOMMERCE_BROWSE = "/ecommerce/product/browse.xhtml";
    private static final String ECOMMERCE_COMPARE = "/ecommerce/product/compare.xhtml";
    private static final String ECOMMERCE_INK_TONER = "/ecommerce/product/inkTonerSearch.xhtml";
    private static final String ECOMMERCE_CART = "/ecommerce/shoppingCart/cart.xhtml";
    private static final String ECOMMERCE_ORDER_HISTORY = "/ecommerce/order/orderHistory.xhtml";
    private static final String ECOMMERCE_USER_FAVORITES = "/ecommerce/product/favorites.xhtml";
    private static final String ECOMMERCE_NEW_PUNCHOUT = "/ecommerce/marketplace/welcome.xhtml";
    private static final String ECOMMERCE_COMPANY_FAVORITES = "/ecommerce/product/companyFavorites.xhtml";
    private static final String ECOMMERCE_RETURN_CART = "/ecommerce/marketplace/returnCart.xhtml";
    private static final long serialVersionUID = 1L;
    private static final String REQUEST_ITEM = "/ecommerce/product/requestItem.xhtml";
    private static final String ITEM_NOT_FOUND = "/ecommerce/errors/itemNotFound.xhtml";
    private static final String ECOMMERCE_PUNCHOUT_CONTINUE_SHOPPING = "/ecommerce/marketplace/punchoutWindow.xhtml";
    private static final String ECOMMERCE_PUNCHOUT_EDIT = "/ecommerce/marketplace/punchoutWindow.xhtml";
    public static final String PASSWORD_RESET_INFO_PAGE = "/ecommerce/user/passwordResetInfo.xhtml";
    public static final String PASSWORD_CHANGED_PAGE = "/ecommerce/user/passwordChangedConfirmation.xhtml";
    public static final String ECOMMERCE_TASK_LIST = "/ecommerce/task/taskList.xhtml";

    public String getPasswordChangedPage() {
        return url(PASSWORD_CHANGED_PAGE);
    }

    public String getPasswordResetInfoPage() {
        return url(PASSWORD_RESET_INFO_PAGE);
    }

    public String getResetPassword() {
        return url(RESET_PASSWORD_PAGE);
    }

    public String getPublicResetPassword() {
        return url(PUBLIC_RESET_PASSWORD_PAGE);
    }

    public String getMyAccount() {
        return url(MY_ACCOUNT_PAGE);
    }

    public String getHome() {
        return url(ECOMMERCE_HOME_PAGE);
    }

    public String getCashout() {
        return url(ECOMMERCE_CASHOUT);
    }

    public String getBrowse() {
        return url(ECOMMERCE_BROWSE);
    }

    public String getCompare() {
        return url(ECOMMERCE_COMPARE);
    }

    public String getCart() {
        return url(ECOMMERCE_CART);
    }

    public String getOrderHistory() {
        return url(ECOMMERCE_ORDER_HISTORY);
    }

    public String getUserFavorites() {
        return url(ECOMMERCE_USER_FAVORITES);
    }

    public String getCompanyFavorites() {
        return url(ECOMMERCE_COMPANY_FAVORITES);
    }

    public String getRequestItem() {
        return url(REQUEST_ITEM);
    }

    public String getItemNotFound() {
        return url(ITEM_NOT_FOUND);
    }

    public String getReturnCart() {
        return url(ECOMMERCE_RETURN_CART);
    }

    private String url(String pathEnding) {
        ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
        StringBuilder toReturn = new StringBuilder();
        toReturn.append(context.getRequestContextPath());
        toReturn.append(pathEnding);
        return toReturn.toString();
    }

    public String getPunchout() {
        return url(ECOMMERCE_PUNCHOUT);
    }

    public String getNewPunchout() {
        return url(ECOMMERCE_NEW_PUNCHOUT);
    }

    public String getPunchoutContinueShopping() {
        return url(ECOMMERCE_PUNCHOUT_CONTINUE_SHOPPING);
    }

    public String getPunchoutEditOrder() {
        return url(ECOMMERCE_PUNCHOUT_EDIT);
    }

    public String getLookahead() {
        return url(ECOMMERCE_PRODUCT_LOOKAHEAD_ENDPOINT);

    }

    public String getHostName() {
        String hostName = "";

        try {
            hostName = InetAddress.getLocalHost().getHostName();
        }
        catch (Exception exp) {

        }
        return hostName;
    }

    public String getSmartSearchLookahead() {
        return url(ECOMMERCE_SMART_SEARCH_LOOKAHEAD);
    }

    public String getSmartSearchCartridgeLookahead() {
        return url(ECOMMERCE_SMART_SEARCH_CARTRIDGE_NUMBER_LOOKAHEAD);
    }

    public String getInkTonerSearch() {
        return url(ECOMMERCE_INK_TONER);
    }

    public String getTaskList() {
        return url(ECOMMERCE_TASK_LIST);
    }

    public String getSmartSearchModelLookahead() {
        return url(ECOMMERCE_SMART_SEARCH_MODEL_NUMBER_LOOKAHEAD);
    }

    public String getCartridgeLookahead() {
        return url(ECOMMERCE_CARTRIDGE_LOOKAHEAD_ENDPOINT);
    }

    public String getSolrModelLookahead() {
        return url(ECOMMERCE_MODEL_LOOKAHEAD_ENDPOINT);
    }
}

phoenix-shopping/src/main/webapp/ecommerce/user/createUserRequest.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:c="http://java.sun.com/jstl/core"
	template="/WEB-INF/templates/ecommerceLoginTemplate.xhtml">
	

	<ui:define name="page_content">
		<div id="loginContainerMain">
			<div id="login-content" class="row-fluid">
				<p>#{display['userRequest.notice']}</p>
				<ul>				
					<h:panelGroup rendered="#{loginBean.isMarfieldSubdomain}">	
						<li>If you normally purchase through <span style="color:red;">SAP</span> or <span style="color:red;">ARIBA</span>, there’s no need to register. Instead, log in through SAP or ARIBA.</li>
						<li>If you normally purchase through the <span style="color:red;">PepsiCo</span> Intranet link or web address, please continue registration below.</li>					
					</h:panelGroup>
					<h:panelGroup rendered="#{not loginBean.isMarfieldSubdomain}">
						<li>#{pageCssBean.createUserRequestInstructions}</li>
					</h:panelGroup>
				</ul>
				<div>
					<div class="span5 loginMgn-left" style="width: 850px">
						<h2>#{display['userRequest.header']}</h2>
						<hr />
						<h:form id="userRequest" class="form-inline">
                                                    <h:messages style="color:red;"/>
	                        <h:panelGroup rendered="#{loginBean.isMarfieldSubdomain}">
	                            <div >
									<h:outputLabel for="company" value="Company Name*:" />
									<h:inputText id="company"
										value="#{userCreationRequestBean.companyName}" required="true" requiredMessage="The 'Company Name' must be provided." />
								</div>
							</h:panelGroup>
							<div>
								<h:outputLabel for="first" value="First Name*:"/>
								<h:inputText id="first"
									value="#{userCreationRequestBean.firstName}" required="true" requiredMessage="The 'First Name' must be provided."/>
							</div>
							<div>
								<h:outputLabel for="last" value="Last Name*:"/>
								<h:inputText id="last"
									value="#{userCreationRequestBean.lastName}" required="true" requiredMessage="The 'Last Name' must be provided."/>
							</div>
							
							<div>
								<h:outputLabel for="email" value="Email Address*:" />
								<h:inputText id="email" value="#{userCreationRequestBean.email}" validator="#{userCreationRequestBean.validateEmailAddress}" required="true" requiredMessage="The 'Email Address' must be provided." />
							</div>
							<div>
								<h:outputLabel for="password" value="Password*:" />
								<h:inputSecret id="password" value="#{userCreationRequestBean.password}" required="true" requiredMessage="A Password must be provided." styleClass="registrationPassword"/>
							</div>
							<h:panelGroup rendered="#{loginBean.isMarfieldSubdomain}">
								<div>
									<h:outputLabel value="Phone (XXX) XXX-XXXX *:" />
									<h:inputText id="phone"
										value="#{userCreationRequestBean.phoneNumberValidationBean.phoneNumberReadable}"
										maxlength="14" required="true"
										validatorMessage="Number must be of the format (XXX) XXX-XXXX or X-XXX-XXX-XXXX."
										requiredMessage="#{display['userRequest.phoneNumber.field.lineNumber.required']}">
										<f:validateRegex
											pattern="#{userCreationRequestBean.phoneNumberValidationBean.phoneNumberReadableRegex}" />
									</h:inputText>
									<h:outputLabel for="ext" value="Ext:" styleClass="inline-input" />
									<h:inputText id="ext" size="4"
										value="#{userCreationRequestBean.ext}" />
								</div>
							</h:panelGroup>
							 <h:panelGroup rendered="#{loginBean.isMarfieldSubdomain}">
								<div>
									<div>
										<h3>Location</h3>
									</div>
	
									<div>
										<h:outputLabel value="Address 1*:"/>
										<h:inputText value="#{userCreationRequestBean.address1New}" required="true" requiredMessage="The 'Address' must be provided." />
									</div>
									<div>
										<h:outputLabel value="Address 2:" />
										<h:inputText value="#{userCreationRequestBean.address2New}" />
									</div>
									<div>
										<h:outputLabel value="City*:" />
										<h:inputText value="#{userCreationRequestBean.cityNew}" required="true" requiredMessage="The 'City' must be provided." />
									</div>
									<div>
										<h:outputLabel value="State*:" />
										<h:inputText value="#{userCreationRequestBean.stateNew}" size="5" required="true" requiredMessage="The 'State' must be provided."/>
										<h:outputLabel value="Zip*:" styleClass="inline-input" />
										<h:inputText size="9"
											value="#{userCreationRequestBean.zipNew}" required="true" requiredMessage="The 'Zip' must be provided."/>
									</div>
								
								</div>
							</h:panelGroup>
							
							<h:panelGroup id="alreadyUsedMessage">
								<div style='color:red;#{userCreationRequestBean.validAddress?"display:none":""}'>
									This user is already registered in our system. To reset your password, click<a href="#{linksBean.publicResetPassword}?username=#{userCreationRequestBean.email}"> here</a>.
								</div>
							</h:panelGroup>					
														
							<div class="submit">
								<h:commandButton id="submit" value="Submit"
									action="#{userCreationRequestBean.submit()}"
									styleClass="btn-primary btn-large btn-info pull-left">
								</h:commandButton>
							</div>
						</h:form>
					</div>
				</div>
			</div>
		</div>
	</ui:define>

</ui:composition>

phoenix-shopping/src/main/webapp/ecommerce/user/missingDepartmentsInfo.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:rich="http://richfaces.org/rich"
                xmlns:a4j="http://richfaces.org/a4j"
                xmlns:c="http://java.sun.com/jstl/core"
                template="/WEB-INF/templates/ecommerceLoginTemplate.xhtml">

    <ui:define name="page_content">
        <div>
            <h2>Error: You have not filled out all required fields for the Department. Please, fill in all fields before adding your department to the table!</h2>
            <h3><a href="#{loginBean.userRegistrationPage}"><u>Please click here to return to the user registration page.</u></a></h3>
        </div>
    </ui:define>

</ui:composition>

phoenix-shopping/src/main/webapp/ecommerce/user/passwordChangedConfirmation.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:rich="http://richfaces.org/rich"
                xmlns:a4j="http://richfaces.org/a4j"
                template="/WEB-INF/templates/ecommerceLoginTemplate.xhtml">
    <ui:define name="page_content">
    <div>
    		<h3>Your Password has been changed.</h3>
    		<h:form>
    			<a4j:commandButton value="Back to login page" action="#{loginBean.logoutAndGoToLoginPage()}" />
    		</h:form>
   	</div>   
    </ui:define>

</ui:composition>

phoenix-shopping/src/main/webapp/ecommerce/user/passwordResetInfo.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:rich="http://richfaces.org/rich"
                xmlns:a4j="http://richfaces.org/a4j"
                xmlns:c="http://java.sun.com/jstl/core"
                template="/WEB-INF/templates/ecommerceLoginTemplate.xhtml">

    <ui:define name="page_content">
    	<div>
    		<h3>Your Password has been reset successfully. You will receive an email with further instructions.</h3>
    		<h:form>
    			<a4j:commandButton value="Back to login page" action="#{loginBean.logoutAndGoToLoginPage()}" />
    		</h:form>
    	</div>
    </ui:define>

</ui:composition>

phoenix-shopping/src/main/webapp/ecommerce/user/thankYouUserRegistration.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:rich="http://richfaces.org/rich"
                xmlns:a4j="http://richfaces.org/a4j"
                xmlns:c="http://java.sun.com/jstl/core"
                template="/WEB-INF/templates/ecommerceLoginTemplate.xhtml">

    <ui:define name="page_content">
        <div>
            <h2>Thank you! Your request has been submitted and will be processed by our Customer Service Team.</h2>
            <h3><a href="#{loginBean.homePage}"><u>Please click here to return to the login page.</u></a></h3>
        </div>
    </ui:define>

</ui:composition>