phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/HomeBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apd.phoenix.shopping.view.jsf.bean;

import com.apd.phoenix.service.product.Product;
import com.apd.phoenix.shopping.view.jsf.bean.search.SearchEngine;
import com.apd.phoenix.shopping.view.jsf.bean.utils.LinksBean;
import com.apd.phoenix.core.PageNumberDisplay;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import javax.annotation.PostConstruct;
import javax.ejb.LocalBean;
import javax.ejb.Stateful;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author dcnorris
 */
@Named
@Stateful
@LocalBean
//TODO consider converting this to conversation scope
@SessionScoped
public class HomeBean implements Serializable {

    private static final long serialVersionUID = 1L;
    @Inject
    private LinksBean linksBean;
    private static final Logger logger = LoggerFactory.getLogger(HomeBean.class);
    private List<Product> featuredProductList = new ArrayList<>();
    private int previousPage;
    private int numFound;
    private int randomSort;
    private PageNumberDisplay pageDisplay;
    public static final PageNumberDisplay.PageSize PAGE_SIZE = PageNumberDisplay.PageSize.SIX;
    public static final int ENTRIES_PER_ROW = 3;
    @Inject
    private SearchEngine searchEngine;

    @PostConstruct
    public void init() {
        numFound = searchEngine.featuredProductsFound();
        pageDisplay = new PageNumberDisplay(numFound);
        pageDisplay.setPageSize(PAGE_SIZE);
        Random rand = new Random();
        randomSort = rand.nextInt(99999);
    }
    
    public List<Product> getFeaturedProductList() {
        if (pageDisplay.getPage() != previousPage) {
        	if (logger.isDebugEnabled()) {
        		logger.debug("Sending request for featured products");
        	}
            previousPage = pageDisplay.getPage();
            featuredProductList = searchEngine.featuredProductList((pageDisplay.getPage() - 1) * pageDisplay.getSize(), randomSort);
        }
        return featuredProductList;
    }

    public int getPreviousPage() {
        return previousPage;
    }

    public void setPreviousPage(int previousPage) {
        this.previousPage = previousPage;
    }

    public PageNumberDisplay getPageDisplay() {
        return pageDisplay;
    }

    public void setPageDisplay(PageNumberDisplay pageDisplay) {
        this.pageDisplay = pageDisplay;
    }
    
    public int getENTRIES_PER_ROW() {
    	return ENTRIES_PER_ROW;
    }

}

phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/MarketingImagesBean.java
package com.apd.phoenix.shopping.view.jsf.bean;

import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.inject.Named;
import org.apache.commons.lang.StringUtils;
import com.apd.phoenix.core.StringEscape;
import com.apd.phoenix.core.utility.TenantConfigRepository;
import com.apd.phoenix.service.business.CatalogBp;
import com.apd.phoenix.service.model.CarouselDisplay;
import com.apd.phoenix.service.model.Catalog;
import com.apd.phoenix.service.model.Credential;
import com.apd.phoenix.service.model.CredentialPropertyType.CredentialPropertyTypeEnum;
import com.apd.phoenix.service.model.CredentialXCredentialPropertyType;
import com.apd.phoenix.service.persistence.multitenancy.impl.CurrentTenantIdentifierResolverImpl;
import com.apd.phoenix.shopping.view.jsf.bean.login.CredentialSelectionBean;

/**
 *
 * @author anicholson
 */
@Named
public class MarketingImagesBean {

    private static final String IMAGE_LINK_DESTINATION_SUFFIX = "ImageLinkDestination";
    private static final String IMAGE_DIRECTORY = "/images/marketing/";

    private static final String PROPERTIES_PREFIX = "image.name.";

    @Inject
    CredentialSelectionBean credentialSelectionBean;

    @Inject
    CatalogBp catalogBp;

    public String getBannerUrl() {
        if (credentialSelectionBean.getCurrentCredential() != null
                && credentialSelectionBean.getCurrentCredential().getProperties() != null) {
            String bannerName = findBannerName(credentialSelectionBean.getCurrentCredential());
            if (StringUtils.isNotEmpty(bannerName)) {
                return getImageDirectoryURL() + StringEscape.escapeForUrl(bannerName);
            }
        }
        return getImageUrl("banner");
    }

    private String findBannerName(Credential currentCredential) {
        for (CredentialXCredentialPropertyType credentialPropety : currentCredential.getProperties()) {
            if (credentialPropety.getType() != null
                    && CredentialPropertyTypeEnum.BANNER_NAME.getValue().equals(credentialPropety.getType().getName())) {
                return credentialPropety.getValue();
            }
        }
        return null;
    }

    public static String getImageUrl(String location) {
        String imageName = TenantConfigRepository.getInstance().getProperties("themeMap").getProperty(
                PROPERTIES_PREFIX + location);
        String url = getImageDirectoryURL() + StringEscape.escapeForUrl(imageName);
        return url;
    }

    public String getImageLinkDestination(String location) {

        String url = "";
        Credential cred = credentialSelectionBean.getCurrentCredential();

        if (cred != null) {
            url = cred.getPropertyValueByType(location + IMAGE_LINK_DESTINATION_SUFFIX);
        }

        if (StringUtils.isEmpty(url)) {
            url = TenantConfigRepository.getInstance().getProperties("themeMap").getProperty(
                    "image.link.destination." + location);
        }
        return url;
    }

    private static String getImageDirectoryURL() {
        Long tenantId = CurrentTenantIdentifierResolverImpl.getCurrentTenant();
        return TenantConfigRepository.getInstance().getPropertiesByTenantId(tenantId, "tenant").getProperty(
                "content.service.secure.tenant.domain")
                + IMAGE_DIRECTORY;

    }

    public String getTopHomeImageUrl() {
        if (isCatalogNotNull()
                && StringUtils.isNotBlank(credentialSelectionBean.getCurrentCredential().getCatalog()
                        .getMarketingImageUrlTop())) {
            return credentialSelectionBean.getCurrentCredential().getCatalog().getMarketingImageUrlTop();
        }
        else {
            return getImageUrl("home1");
        }
    }

    public String getTopHomeImageLinkDestination() {
        if (isCatalogNotNull()
                && StringUtils.isNotBlank(credentialSelectionBean.getCurrentCredential().getCatalog()
                        .getMarketingImageLinkUrlTop())) {
            return credentialSelectionBean.getCurrentCredential().getCatalog().getMarketingImageLinkUrlTop();
        }
        else {
            return getImageLinkDestination("home1");
        }
    }

    public String getBottomHomeImageUrl() {
        if (isCatalogNotNull()
                && StringUtils.isNotBlank(credentialSelectionBean.getCurrentCredential().getCatalog()
                        .getMarketingImageUrlBottom())) {
            return credentialSelectionBean.getCurrentCredential().getCatalog().getMarketingImageUrlBottom();
        }
        else {
            return getImageUrl("home2");
        }
    }

    public String getBottomHomeImageLinkDestination() {
        if (isCatalogNotNull()
                && StringUtils.isNotBlank(credentialSelectionBean.getCurrentCredential().getCatalog()
                        .getMarketingLinkUrlBottom())) {
            return credentialSelectionBean.getCurrentCredential().getCatalog().getMarketingLinkUrlBottom();
        }
        else {
            return getImageLinkDestination("home2");
        }
    }

    private boolean isCatalogNotNull() {
        return credentialSelectionBean.getCurrentCredential() != null
                && credentialSelectionBean.getCurrentCredential().getCatalog() != null;
    }

    public List<CarouselDisplay> getHomePageCarouselDisplays() {
        List<CarouselDisplay> display = new ArrayList<CarouselDisplay>();
        if (isCatalogNotNull()) {
            Catalog catalog = catalogBp.hydrateCarousel(credentialSelectionBean.getCurrentCredential().getCatalog());
            if (!catalog.getCarouselDisplayItems().isEmpty()) {
                display.addAll(catalog.getCarouselDisplayItems());
            }
        }
        if (display.isEmpty()) {
            CarouselDisplay defaultImage = new CarouselDisplay();
            defaultImage.setBackgroundImageUrl(getImageUrl("ip-banner"));
            defaultImage.setLinkUrl(getImageLinkDestination("ip-banner"));
            display.add(defaultImage);
        }
        return display;
    }

    public int getCarouselQuantity() {
        return getHomePageCarouselDisplays() != null ? getHomePageCarouselDisplays().size() : 0;
    }

}

phoenix-shopping/src/main/webapp/ecommerce/home.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:rich="http://richfaces.org/rich"
                xmlns:a4j="http://richfaces.org/a4j"
                xmlns:apd="http://java.sun.com/jsf/composite/apd"
                template="/WEB-INF/templates/ecommerceHomeTemplate.xhtml">
    <f:metadata>
        <f:event type="preRenderView" listener="#{favoritesBean.refreshPage()}"  />
        <f:event type="preRenderView" listener="#{searchBean.regenerateLastResultsUrl()}"/>
    </f:metadata>
    <ui:define name="page_content">
        <div class="row apdMarginTop container home">
        <div id="homePageCarousel">
    		<ui:repeat var="carousel" value="#{marketingImagesBean.getHomePageCarouselDisplays()}" varStatus="status">
    			<h:panelGroup rendered="#{not empty carousel.backgroundImageUrl}">
	    		<div id="homePageCarousel#{status.index}" class="singleCarouselWrapper">
	    			<h:panelGroup layout="block" styleClass="singleCarouselText" rendered="#{not empty carousel.header or not empty carousel.body 
	    					or (not empty carousel.linkUrl and not empty carousel.linkText)}">
	    				<h:panelGroup rendered="#{not empty carousel.header}">
	    					<h2>#{carousel.header}</h2>
	    				</h:panelGroup>
	    				<h:panelGroup rendered="#{not empty carousel.body}">
	    					<p>#{carousel.body}</p>
	    				</h:panelGroup>
	    				<h:panelGroup styleClass="singleCarouselLink" rendered="#{not empty carousel.linkUrl and not empty carousel.linkText}">
	    					<a href="#{carousel.linkUrl}">#{carousel.linkText}</a>
	    				</h:panelGroup>
	    			</h:panelGroup>
	    			<a href="#{carousel.linkUrl}"><img src="#{carousel.backgroundImageUrl}" class="singleCarouselImageHomePage" /></a>
	    		</div>
	    		</h:panelGroup>
    		</ui:repeat>
    	</div>
            <div id="daily-offer-wrapper">
            	<div  style="margin-bottom: 20px;">
            	<a target="_blank" href="#{marketingImagesBean.getTopHomeImageLinkDestination()}">
            		<img src="#{marketingImagesBean.getTopHomeImageUrl()}" />
            	</a>
            	</div>
            	<div>
            	<a href="#{marketingImagesBean.getBottomHomeImageLinkDestination()}">
            		<img src="#{marketingImagesBean.getBottomHomeImageUrl()}" />
            	</a>
            	</div>
            </div>
            <h:form id="homePageForm">
                <div class="span10 mobileHide">
                    <div class="company-featured-products">
                                    #{display['home.featured']}
                    </div>
                    <div class="row-fluid FeaturedWidth">
                        <div class="span12">
                            <div id="featuredProductBlock">                                
                                <h:panelGroup id="coreProductWidget" layout="block" >
                                    <ui:repeat var="product" value="#{homeBean.featuredProductList}" varStatus="listStatus">
                                    	<h:panelGroup rendered="#{listStatus.index % homeBean.ENTRIES_PER_ROW == 0}">
                                    		<!-- Adds span12 wrapper for each group of elements, to ensure they are all on the same row -->
                                    		<h:outputText value="&lt;div class=&quot;span12&quot;&gt;" escape="false" />
                                    	</h:panelGroup>
                                        <div class="span3 featured-product">
                                            <div>
                                                <a href="#{product.detailsLink}" class="thumbnail">
                                                    <img src="#{product.mainImageUrl}" alt="Image" class="homePageImage"/>
                                                </a>
                                            </div>
                                            <div class="product-info">
                                                <div class="manufacturer fixed-height-short">#{product.manufacturerName}</div>
                                                <div class="title fixed-height-tall" style="word-break: break-word"><a href="#{product.detailsLink}">#{product.name}</a></div>
                                                <div class="sku fixed-height-short">
                                                    <strong>SKU:</strong>#{product.customerSku}
                                                </div>
                                                <div class="product-icons fixed-height-short">
                                                    <a4j:repeat rendered="#{not empty product.iconMap.keySet()}" value="#{viewUtils.mapToList(product.iconMap)}" var="entry" rowKeyVar="index">
                                                        <img  src="#{credentialSelectionBean.getIconUrl(entry.key)}" alt="Product Icon Image" class="productIconImage" rel="tooltip" title="#{entry.value}" />
                                                    </a4j:repeat>
                                                </div>
                                                <apd:addToCart product="#{product}" narrow="true"/>
                                            </div>
                                        </div>
                                    	<h:panelGroup rendered="#{listStatus.index % homeBean.ENTRIES_PER_ROW == (homeBean.ENTRIES_PER_ROW - 1) or listStatus.last}">
                                    		<h:outputText value="&lt;/div&gt;" escape="false" />
                                    	</h:panelGroup>
                                    </ui:repeat>
                                </h:panelGroup>                                    
                                <apd:pagination pageDisplay="#{homeBean.pageDisplay}" render="homePageForm" />
                            </div>
                        </div>
                    </div>                    
                </div>
            </h:form>
        </div>
        <div id="push"></div>
        <script type="text/javascript">
	    	$(document).ready(function() {
				runslide(0);
	    	});
			
			function runslide(value) {

				//resets carousel index if all items have been seen
				if (value >= #{marketingImagesBean.carouselQuantity}) {
					value = 0;
				}

				//if no items in the carousel, just returns
				if (#{marketingImagesBean.carouselQuantity == 0}) {
					return;
				} else if (#{marketingImagesBean.carouselQuantity == 1}) {
					//if one item in the carousel, that item is displayed, and returns
					jQuery("#homePageCarousel0").fadeIn(1500);
				} else {
					//if there is more than one item in the carousel, the current item is displayed,
					//then the index is incremented to display the next item
					jQuery("#homePageCarousel" + value).fadeIn(1500).delay(5500).fadeOut(1500, function() {runslide(value + 1);});
				}
			}
		</script>
    </ui:define>

</ui:composition>