phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/cashout/AddToCartDemoBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apd.phoenix.shopping.view.jsf.bean.cashout;

import com.apd.phoenix.service.model.Item;
import com.apd.phoenix.shopping.view.jsf.bean.data.MockDataFactory;
import com.google.gson.Gson;
import java.util.List;
import javax.ejb.Stateful;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author dcnorris
 */
@Named
@Stateful
@SessionScoped
public class AddToCartDemoBean {

    private ItemJsonContainer tempNotification;

    private static final Logger LOGGER = LoggerFactory.getLogger(AddToCartDemoBean.class);

    public String addSelectedItemsToCart() {
        StringBuilder jsonResponse = new StringBuilder();
        jsonResponse.append("[");
        List<Item> items = MockDataFactory.ItemFactory.getItemList(2);

        jsonResponse.append(getJSON(items.get(0), "hardSubstitute"));
        jsonResponse.append(",");
        jsonResponse.append(getJSON(items.get(1), "softSubstitute"));
        jsonResponse.append("]");
        LOGGER.info("Response: ");
        LOGGER.info(jsonResponse.toString());
        return jsonResponse.toString();
    }

    private String getJSON(Item item, String type) {
        ItemJsonContainer obj = new ItemJsonContainer();
        obj.setImgURL("/shopping/resources/img/image_placement/75x75");
        obj.setItemName(item.getName());
        obj.setItemPrice("3.99");
        obj.setItemQty("2");
        obj.setMessageHeader("Item Added Successfully!!!");

        Gson gson = new Gson();

        // convert java object to JSON format,
        // and returned as JSON formatted string
        String json = gson.toJson(obj);

        return json;
    }

    public void addToTempList() {
        //        notificationList.add(tempNotification);
        LOGGER.info("addToTempList Method Called");
    }

    public ItemJsonContainer getTempNotification() {
        return tempNotification;
    }

    public void setTempNotification(ItemJsonContainer tempNotification) {
        this.tempNotification = tempNotification;
    }

}

phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/cashout/AddToFavoritesListBean.java
package com.apd.phoenix.shopping.view.jsf.bean.cashout;

import javax.ejb.Stateful;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.apd.phoenix.service.business.AccountXCredentialXUserBp;
import com.apd.phoenix.service.business.CatalogXItemBp;
import com.apd.phoenix.service.business.FavoritesListBp;
import com.apd.phoenix.service.model.CatalogXItem;
import com.apd.phoenix.service.model.FavoritesList;
import com.apd.phoenix.service.product.Product;
import com.apd.phoenix.shopping.view.jsf.bean.favorites.FavoritesBean;
import com.apd.phoenix.shopping.view.jsf.bean.login.CredentialSelectionBean;

@Named
@Stateful
@SessionScoped
public class AddToFavoritesListBean {

    private static final Logger logger = LoggerFactory.getLogger(AddToFavoritesListBean.class);

    @Inject
    private AccountXCredentialXUserBp accountXCredentialXUserBp;
    @Inject
    private CredentialSelectionBean credentialSelectionBean;
    @Inject
    private FavoritesBean favoritesBean;
    @Inject
    private FavoritesListBp favoritesListBp;
    @Inject
    private CatalogXItemBp catalogXItemBp;
    private String selectedFavoritesListName;
    private CatalogXItem catalogXItem;
    private boolean productAddedToList = false;
    private Product product;

    private long getMatchingListID() {
        FavoritesList list = accountXCredentialXUserBp.getFavoritesListByNameAndCredential(selectedFavoritesListName,
                this.credentialSelectionBean.getCurrentAXCXU());
        if (list != null) {
            return list.getId();
        }
        return -1;
    }

    public void setupAddToList(Long productId) {
        if (this.product == null) {
            this.product = new Product();
        }
        this.product.setId(productId);
    }

    public void addProductToFavorites() {
        if (product.getId() != null && product.getId() != 0) {
            catalogXItem = catalogXItemBp.findById(product.getId(), CatalogXItem.class);
        }
        else {
            logger.error("Could not determine catxitem to add to favorites list");
            return;
        }
        FavoritesList selectedList = new FavoritesList();
        selectedList.setName(selectedFavoritesListName);
        selectedList.setId(getMatchingListID());
        if (selectedList.getId() == -1) {
            //Add new list
            favoritesBean.addNewUserList(selectedFavoritesListName);
            selectedList.setId(getMatchingListID());
            if (selectedList.getId() == -1) {
                logger.error("Could not add new favorites list.");
                FacesContext.getCurrentInstance().addMessage(null,
                        new FacesMessage("Error creating new favorites list"));
            }
            selectedList = favoritesListBp.searchByExactExample(selectedList, 0, 0).get(0);
            selectedList = favoritesListBp.findById(selectedList.getId(), FavoritesList.class);
            selectedList.getUserItems().add(catalogXItem);
            selectedList = favoritesListBp.update(selectedList);
            favoritesBean.refreshPage();
        }
        else {
            selectedList = favoritesListBp.searchByExactExample(selectedList, 0, 0).get(0);
            selectedList = favoritesListBp.findById(selectedList.getId(), FavoritesList.class);
            selectedList.getUserItems().add(catalogXItem);
            selectedList = favoritesListBp.update(selectedList);
            favoritesBean.refreshPage();
        }
        favoritesBean.updateUserFavoritesList();
        //this.initializePageData();
        this.productAddedToList = true;
    }

    public String getSelectedFavoritesListName() {
        return selectedFavoritesListName;
    }

    public void setSelectedFavoritesListName(String selectedFavoritesListName) {
        this.selectedFavoritesListName = selectedFavoritesListName;
    }

    public CatalogXItem getCatalogXItem() {
        return catalogXItem;
    }

    public void setCatalogXItem(CatalogXItem catalogXItem) {
        this.catalogXItem = catalogXItem;
    }

    public boolean getProductAddedToList() {
        return productAddedToList;
    }

    public void setProductAddedToList(boolean productAddedToList) {
        this.productAddedToList = productAddedToList;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }
}

phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/cashout/CashoutBeanRetrieveWrapper.java
package com.apd.phoenix.shopping.view.jsf.bean.cashout;

import java.io.IOException;
import java.io.Serializable;
import javax.enterprise.context.Conversation;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Workaround for lock exceptions occurring when calling the "retrieve" method on Cashout.
 * 
 * If an exception occurs on the retrieve method, the page is refreshed several times, which
 * would get around the lock exception. After the last retry, if the error persists, the
 * user is shown an error page as expected.
 * 
 * @author RHC
 *
 */
@Named
@SessionScoped
public class CashoutBeanRetrieveWrapper implements Serializable {

    private static final long serialVersionUID = 1L;

    private static final Logger LOGGER = LoggerFactory.getLogger(CashoutBeanRetrieveWrapper.class);

    private static final int TOTAL_TRIES = 5;

    @Inject
    private CashoutBean cashoutBean;

    @Inject
    private Conversation conversation;

    private int tries = 0;

    public void retrieve() throws IOException {
        if (tries < TOTAL_TRIES) {
            try {
                cashoutBean.retrieve();
                tries = 0;
            }
            catch (Exception e) {
                tries++;
                LOGGER.warn("Reattempting load of cashout page, iteration " + tries);
                if (!conversation.isTransient()) {
                    conversation.end();
                }
                ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
                ec.redirect(((HttpServletRequest) ec.getRequest()).getRequestURI());
            }
            return;
        }
        LOGGER.error("Could not hit cashout page");
        tries = 0;
        throw new RuntimeException();
    }
}

phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/cashout/ConfirmationBean.java
package com.apd.phoenix.shopping.view.jsf.bean.cashout;

import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.inject.Inject;
import javax.inject.Named;
import com.apd.phoenix.web.cashout.CashoutPageContainer;
import com.apd.phoenix.service.model.CustomerOrder;

@Named
@ConversationScoped
public class ConfirmationBean implements Serializable {

    private static final long serialVersionUID = 6904057589417219793L;

    @Inject
    private Conversation conversation;

    private CustomerOrder currentOrder;

    private CashoutPageContainer cashoutPageContainer;

    @PostConstruct
    public void init() {
        if (conversation.isTransient()) {
            conversation.begin();
        }
    }

    public CustomerOrder getCurrentOrder() {
        return currentOrder;
    }

    public void setCurrentOrder(CustomerOrder currentOrder) {
        this.currentOrder = currentOrder;
    }

    public CashoutPageContainer getPageValues() {
        return cashoutPageContainer;
    }

    public void setCashoutPageContainer(CashoutPageContainer container) {
        cashoutPageContainer = container;
    }
}

phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/utils/LinksBean.java
package com.apd.phoenix.shopping.view.jsf.bean.utils;

import java.io.Serializable;
import java.net.InetAddress;
import javax.ejb.Stateless;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Named;

/**
 * This is a utility bean, used to generate URLs for the shopping site.
 * 
 * @author RHC
 *
 */
@Named
@Stateless
public class LinksBean implements Serializable {

    private static final String ECOMMERCE_PRODUCT_LOOKAHEAD_ENDPOINT = "/rest/typeahead/mainSearch/";
    private static final String ECOMMERCE_CARTRIDGE_LOOKAHEAD_ENDPOINT = "/rest/typeahead/cartridgeSearch/";
    private static final String ECOMMERCE_MODEL_LOOKAHEAD_ENDPOINT = "/rest/typeahead/modelSearch/";
    private static final String ECOMMERCE_SMART_SEARCH_LOOKAHEAD = "/rest/typeahead/smartSearch/";
    private static final String ECOMMERCE_SMART_SEARCH_CARTRIDGE_NUMBER_LOOKAHEAD = "/rest/typeahead/smartSearch/cartridge/";
    private static final String ECOMMERCE_SMART_SEARCH_MODEL_NUMBER_LOOKAHEAD = "/rest/typeahead/smartSearch/model/";
    private static final String PUBLIC_RESET_PASSWORD_PAGE = "/ecommerce/user/resetPassword.xhtml";
    private static final String RESET_PASSWORD_PAGE = "/ecommerce/account/resetPassword.xhtml";
    public static final String PASSWORD_EXPIRED_PAGE = "/ecommerce/account/passwordExpired.xhtml";
    private static final String MY_ACCOUNT_PAGE = "/ecommerce/account/manage.xhtml";
    private static final String ECOMMERCE_HOME_PAGE = "/ecommerce/home.xhtml";
    private static final String ECOMMERCE_CASHOUT = "/ecommerce/cashout/checkout.xhtml";
    private static final String ECOMMERCE_PUNCHOUT = "/ecommerce/marketplace/returnCart.xhtml";
    private static final String ECOMMERCE_BROWSE = "/ecommerce/product/browse.xhtml";
    private static final String ECOMMERCE_COMPARE = "/ecommerce/product/compare.xhtml";
    private static final String ECOMMERCE_INK_TONER = "/ecommerce/product/inkTonerSearch.xhtml";
    private static final String ECOMMERCE_CART = "/ecommerce/shoppingCart/cart.xhtml";
    private static final String ECOMMERCE_ORDER_HISTORY = "/ecommerce/order/orderHistory.xhtml";
    private static final String ECOMMERCE_USER_FAVORITES = "/ecommerce/product/favorites.xhtml";
    private static final String ECOMMERCE_NEW_PUNCHOUT = "/ecommerce/marketplace/welcome.xhtml";
    private static final String ECOMMERCE_COMPANY_FAVORITES = "/ecommerce/product/companyFavorites.xhtml";
    private static final String ECOMMERCE_RETURN_CART = "/ecommerce/marketplace/returnCart.xhtml";
    private static final long serialVersionUID = 1L;
    private static final String REQUEST_ITEM = "/ecommerce/product/requestItem.xhtml";
    private static final String ITEM_NOT_FOUND = "/ecommerce/errors/itemNotFound.xhtml";
    private static final String ECOMMERCE_PUNCHOUT_CONTINUE_SHOPPING = "/ecommerce/marketplace/punchoutWindow.xhtml";
    private static final String ECOMMERCE_PUNCHOUT_EDIT = "/ecommerce/marketplace/punchoutWindow.xhtml";
    public static final String PASSWORD_RESET_INFO_PAGE = "/ecommerce/user/passwordResetInfo.xhtml";
    public static final String PASSWORD_CHANGED_PAGE = "/ecommerce/user/passwordChangedConfirmation.xhtml";
    public static final String ECOMMERCE_TASK_LIST = "/ecommerce/task/taskList.xhtml";

    public String getPasswordChangedPage() {
        return url(PASSWORD_CHANGED_PAGE);
    }

    public String getPasswordResetInfoPage() {
        return url(PASSWORD_RESET_INFO_PAGE);
    }

    public String getResetPassword() {
        return url(RESET_PASSWORD_PAGE);
    }

    public String getPublicResetPassword() {
        return url(PUBLIC_RESET_PASSWORD_PAGE);
    }

    public String getMyAccount() {
        return url(MY_ACCOUNT_PAGE);
    }

    public String getHome() {
        return url(ECOMMERCE_HOME_PAGE);
    }

    public String getCashout() {
        return url(ECOMMERCE_CASHOUT);
    }

    public String getBrowse() {
        return url(ECOMMERCE_BROWSE);
    }

    public String getCompare() {
        return url(ECOMMERCE_COMPARE);
    }

    public String getCart() {
        return url(ECOMMERCE_CART);
    }

    public String getOrderHistory() {
        return url(ECOMMERCE_ORDER_HISTORY);
    }

    public String getUserFavorites() {
        return url(ECOMMERCE_USER_FAVORITES);
    }

    public String getCompanyFavorites() {
        return url(ECOMMERCE_COMPANY_FAVORITES);
    }

    public String getRequestItem() {
        return url(REQUEST_ITEM);
    }

    public String getItemNotFound() {
        return url(ITEM_NOT_FOUND);
    }

    public String getReturnCart() {
        return url(ECOMMERCE_RETURN_CART);
    }

    private String url(String pathEnding) {
        ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
        StringBuilder toReturn = new StringBuilder();
        toReturn.append(context.getRequestContextPath());
        toReturn.append(pathEnding);
        return toReturn.toString();
    }

    public String getPunchout() {
        return url(ECOMMERCE_PUNCHOUT);
    }

    public String getNewPunchout() {
        return url(ECOMMERCE_NEW_PUNCHOUT);
    }

    public String getPunchoutContinueShopping() {
        return url(ECOMMERCE_PUNCHOUT_CONTINUE_SHOPPING);
    }

    public String getPunchoutEditOrder() {
        return url(ECOMMERCE_PUNCHOUT_EDIT);
    }

    public String getLookahead() {
        return url(ECOMMERCE_PRODUCT_LOOKAHEAD_ENDPOINT);

    }

    public String getHostName() {
        String hostName = "";

        try {
            hostName = InetAddress.getLocalHost().getHostName();
        }
        catch (Exception exp) {

        }
        return hostName;
    }

    public String getSmartSearchLookahead() {
        return url(ECOMMERCE_SMART_SEARCH_LOOKAHEAD);
    }

    public String getSmartSearchCartridgeLookahead() {
        return url(ECOMMERCE_SMART_SEARCH_CARTRIDGE_NUMBER_LOOKAHEAD);
    }

    public String getInkTonerSearch() {
        return url(ECOMMERCE_INK_TONER);
    }

    public String getTaskList() {
        return url(ECOMMERCE_TASK_LIST);
    }

    public String getSmartSearchModelLookahead() {
        return url(ECOMMERCE_SMART_SEARCH_MODEL_NUMBER_LOOKAHEAD);
    }

    public String getCartridgeLookahead() {
        return url(ECOMMERCE_CARTRIDGE_LOOKAHEAD_ENDPOINT);
    }

    public String getSolrModelLookahead() {
        return url(ECOMMERCE_MODEL_LOOKAHEAD_ENDPOINT);
    }
}

phoenix-shopping/src/main/webapp/ecommerce/cashout/checkout.xhtml
<!DOCTYPE html> 
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsp/jstl/core"	
                xmlns:forgeview="http://jboss.org/forge/view"
                xmlns:rich="http://richfaces.org/rich"
                xmlns:a4j="http://richfaces.org/a4j"
                xmlns:apd="http://java.sun.com/jsf/composite/apd"
                template="/WEB-INF/templates/ecommerceCashoutTemplate.xhtml">

    <f:metadata>
        <f:event type="preRenderView" listener="#{cashoutBeanRetrieveWrapper.retrieve}">
        </f:event>
    </f:metadata>

    <ui:define name="page_content">
        <h:form id="checkout">
            <div class="row apdMarginTop container">
            <div class="row-fluid">
                <div class="span12 fl-wrapper">
                    <div class="span8 checkoutMsg">
                        Enter the required information and click PLACE ORDER to submit your order.
                    </div>

                    <div class="shoppingBtns pull-right">

                        <div class="borderBottomMobile rightSideBtn rightSideBtnTop">
                        	<c:if test="#{!credentialSelectionBean.isExternalCatalog()}">
                            	<a href="#{linksBean.cart}"><i class="icon-returnAPD"></i>#{display['checkout.return']}</a>
                            </c:if>
                            <c:if test="#{credentialSelectionBean.isExternalCatalog() and !credentialSelectionBean.punchoutSession}">
	                            <a href="#{linksBean.punchoutContinueShopping}" target="#{credentialSelectionBean.isExternalCatalog() ? '_parent' : '_self'}"><i class="icon-returnAPD"></i>#{cashoutBean.generatePunchoutContinueLabel()}</a>
	                            <ui:remove><a href="#{linksBean.punchoutEditOrder}" target="#{credentialSelectionBean.isExternalCatalog() ? '_parent' : '_self'}"><i class="icon-returnAPD"></i>#{cashoutBean.generatePunchoutEditLabel()}</a></ui:remove>
                            </c:if>
                        </div>
                        <div class="borderBottomMobile rightSideBtn rightSideBtnTop mobileHide">
                        	<c:if test="#{!loginBean.isPunchout() and cashoutBean.rfqAllowed}">
                                <h:commandLink value="REQUEST A QUOTE" 
                                	action="#{cashoutBean.createRequestforQuote()}"                                	
                            		styleClass="placeOrderBtnTop #{cashoutBean.placeOrderAllowed ? 'placeOrderBtn' : 'placeOrderBtn btn disabled'}" 
                            		target="#{credentialSelectionBean.isExternalCatalog() ? '_parent' : '_self'}"/>
                            </c:if>
                        </div>
                        <div class="borderBottomMobile rightSideBtn rightSideBtnTop mobileHide">
                        	<c:if test="#{!loginBean.isPunchout()}">
                                <h:commandLink value="PLACE ORDER" 
                                	action="#{cashoutBean.placeOrder()}" 
                                	disabled="#{!cashoutBean.placeOrderAllowed}"
                            		styleClass="placeOrderBtnTop #{cashoutBean.placeOrderAllowed ? 'placeOrderBtn' : 'placeOrderBtn btn disabled'}" 
                            		target="#{credentialSelectionBean.isExternalCatalog() ? '_parent' : '_self'}"/>
                            </c:if>
                            <c:if test="#{loginBean.isPunchout() and cashoutBean.placeOrderAllowed}">
                                <a class="placeOrderBtn placeOrderBtnTop" 
                                		href="#{linksBean.returnCart}" 
                                		target="#{credentialSelectionBean.isExternalCatalog() ? '_parent' : '_self'}">#{cashoutBean.generatePunchoutReturnCartLabel()}</a>
                            </c:if>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <span class="pull-left">
                        <c:if test="#{cashoutBean.placeOrderAllowed}">
                        	<rich:messages style="color:red"/>
                        </c:if>
                        
                       	<h:panelGroup layout="block" rendered="#{not cashoutBean.placeOrderAllowed}" style="color:red">
                       		<h:outputText value="#{cashoutBean.placeOrderDisallowedMessage}" />
                       	</h:panelGroup>
                       	
                       	<h:panelGroup layout="block" rendered="#{cashoutBean.minimumOrderFeeApplies}" style="color:red">
                       		<h:outputText value="#{cashoutBean.minimumOrderFeeMessage}" />
                       	</h:panelGroup>
                    </span>                 
                    <div class="clearfix"></div>
                    <div class="accordion" id="accordion">
                    	<c:if test="#{!loginBean.isPunchout()}">
	                        <ui:include src="/cashout/orderBilling.xhtml">
	                            <ui:param name="order" value="#{cashoutBean.currentOrder}" />
	                            <ui:param name="page" value="#{cashoutBean.pageValues}" />
	                            <ui:param name="isReadOnly" value="#{false}" />
	                        </ui:include>
                        </c:if>
                        <c:if test="#{!loginBean.isPunchout()}">
	                        <ui:include src="/cashout/orderShipping.xhtml">
	                            <ui:param name="order" value="#{cashoutBean.currentOrder}" />
	                            <ui:param name="page" value="#{cashoutBean.pageValues}" />
	                        	<ui:param name="bean" value="#{cashoutBean}" />	
	                            <ui:param name="isReadOnly" value="#{false}" />
	                        </ui:include>
                        </c:if>
                        <ui:include src="/cashout/orderContent.xhtml">
                            <ui:param name="page" value="#{cashoutBean.pageValues}" />
                            <ui:param name="order" value="#{cashoutBean.currentOrder}" />
                            <ui:param name="liToProduct" value="#{lineItemToProduct}" />
                            <ui:param name="isReadOnly" value="#{false}" />
                            <ui:param name="taxNotCalculated" value="#{true}" />
                        </ui:include>
                    </div>
                   	<h:panelGroup layout="block" rendered="#{cashoutBean.upsShippingInfo}">
                   		<h:outputText value="All orders will be shipped UPS Ground. If you require your order to be shipped Next Day or 2nd Day please call 877.245.9122." />
                   	</h:panelGroup>
                </div>
                <div class="span12 fl-wrapper">
                    <div class="span4"></div>
                    <!-- ==== BOTTOM LINKS ==== --> 
                    <div class="shoppingBtns pull-right">

                       	<h:panelGroup layout="block" rendered="#{not cashoutBean.placeOrderAllowed}" style="color:red">
                       		<h:outputText value="#{cashoutBean.placeOrderDisallowedMessage}" />
                       	</h:panelGroup>
                       	
                       	<h:panelGroup layout="block" rendered="#{cashoutBean.minimumOrderFeeApplies}" style="color:red">
                       		<h:outputText value="#{cashoutBean.minimumOrderFeeMessage}" />
                       	</h:panelGroup>
                        
                        <div class="borderBottomMobile rightSideBtn">
                        	<c:if test="#{!credentialSelectionBean.isExternalCatalog()}">
                            	<a href="#{linksBean.cart}" 
                            		target="#{credentialSelectionBean.isExternalCatalog() ? '_parent' : '_self'}"><i class="icon-returnAPD"></i>#{display['checkout.return']}</a>
                            </c:if>
                            <c:if test="#{credentialSelectionBean.isExternalCatalog() and !credentialSelectionBean.punchoutSession}">
	                            <a href="#{linksBean.punchoutContinueShopping}"
	                            	target="#{credentialSelectionBean.isExternalCatalog() ? '_parent' : '_self'}">
	                            	<i class="icon-returnAPD"></i>#{cashoutBean.generatePunchoutContinueLabel()}</a>
	                            <ui:remove><a href="#{linksBean.punchoutEditOrder}" target="#{credentialSelectionBean.isExternalCatalog() ? '_parent' : '_self'}">
	                            	<i class="icon-returnAPD"></i>#{cashoutBean.generatePunchoutEditLabel()}</a></ui:remove>
                            </c:if>
                        </div>
                        <div class="borderBottomMobile rightSideBtn mobileHide">
                        	<c:if test="#{!loginBean.isPunchout() and cashoutBean.rfqAllowed}">
                                <h:commandLink value="REQUEST A QUOTE" 
                                	action="#{cashoutBean.createRequestforQuote()}"                                 	
                            		styleClass="placeOrderBtnTop #{cashoutBean.placeOrderAllowed ? 'placeOrderBtn' : 'placeOrderBtn btn disabled'}" 
                            		target="#{credentialSelectionBean.isExternalCatalog() ? '_parent' : '_self'}"/>
                            </c:if>
                        </div>
                        <div class="borderBottomMobile rightSideBtn mobileHide">
                        	
                            <c:if test="#{!loginBean.isPunchout()}">
                                <h:commandLink 
                                	value="PLACE ORDER" 
                                	action="#{cashoutBean.placeOrder()}" 
                                	disabled="#{!cashoutBean.placeOrderAllowed}"
                                	target="#{credentialSelectionBean.isExternalCatalog() ? '_parent' : '_self'}"
                            		styleClass="#{cashoutBean.placeOrderAllowed ? 'placeOrderBtn' : 'placeOrderBtn btn disabled'}" />
                            </c:if>
                            <c:if test="#{loginBean.isPunchout() and cashoutBean.placeOrderAllowed}">
                                <a class="placeOrderBtn" 
                                	href="#{linksBean.punchout}"
                                	target="#{credentialSelectionBean.isExternalCatalog() ? '_parent' : '_self'}">#{cashoutBean.generatePunchoutReturnCartLabel()}</a>
                            </c:if>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
           </div>
        </h:form>
    </ui:define>
</ui:composition>