phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/PageCssBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apd.phoenix.shopping.view.jsf.bean;

import java.io.Serializable;
import java.util.Properties;
import javax.annotation.PostConstruct;
import javax.ejb.Stateful;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.component.UIInput;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import org.apache.commons.lang.StringUtils;
import com.apd.phoenix.core.StringEscape;
import com.apd.phoenix.core.utility.TenantConfigRepository;
import com.apd.phoenix.service.business.AccountBp;
import com.apd.phoenix.service.business.IpSubdomainRestriction;
import com.apd.phoenix.service.persistence.multitenancy.api.CurrentTenantDomain;
import com.apd.phoenix.service.persistence.multitenancy.impl.CurrentTenantIdentifierResolverImpl;

/**
 * This class is used by the ecommerceMainTemplate.xthml template page to get
 * the appropriate css file for a specific customer.
 * <br /><br />
 * To set a CSS file for a particular account, save the file in
 * phoenix-shopping/src/main/webapp/resources/css/main, then add a property to
 * cssMap.properties and cssMapResponsive.properties, from the root account name
 * to the path of the CSS file.
 *
 * @author RHC
 *
 */
@Named
@Stateful
@RequestScoped
public class PageCssBean implements Serializable {

    private static final long serialVersionUID = 1L;
    private static final String CUSTOM_CSS_URL_SUFFIX = "/phoenix-css/";
    private static final String SUBDOMAIN_IMAGES_SUFFIX = "/images/";
    private static final String SUBDOMAIN_WELCOME_IMAGES_SUFFIX = "welcome-images/";
    private static final String SUBDOMAIN_LOGOS_SUFFIX = "logos/";
    private static final String SUBDOMAIN_CSS_LOCATION = "css/subDomain/";
    private static final String CSS_FILE_EXTENSION = ".css";

    private Properties themeMapProperties;
    private Properties tenantProperties;

    private String staticContentURL;
    private String tenantName;

    @Inject
    private AccountBp accountBp;

    @Inject
    private CurrentTenantDomain currentTenantDomain;

    @PostConstruct
    public void init() {
        tenantName = TenantConfigRepository.getInstance().getTenantNameByDomain(currentTenantDomain.getDomain());
        if (tenantName == null) {
            tenantName = TenantConfigRepository.getInstance().getTenantNameById(
                    CurrentTenantIdentifierResolverImpl.getCurrentTenant());
        }

        staticContentURL = TenantConfigRepository.getInstance().getProperty(tenantName, "tenant",
                "content.service.secure.tenant.domain");
        themeMapProperties = TenantConfigRepository.getInstance().getPropertiesByTenantName(tenantName, "themeMap");
        tenantProperties = TenantConfigRepository.getInstance().getPropertiesByTenantName(tenantName, "tenant");
    }

    public String getSubDomainBasedCssFile() {
        String cssKey = getSubdomainValue();
        if (cssKey.isEmpty() || cssKey.equals(IpSubdomainRestriction.GENERIC_SUBDOMAIN)) {
            return "";
        }
        return staticContentURL + CUSTOM_CSS_URL_SUFFIX + SUBDOMAIN_CSS_LOCATION + StringEscape.escapeForUrl(cssKey)
                + CSS_FILE_EXTENSION;
    }

    public String getSubdomainValue() {
        HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext()
                .getRequest();
        return IpSubdomainRestriction.ipAndDomainInfo(request)[1];
    }

    public String getSubDomainWelcomeMessage() {
        return this.getSubdomainSpecificProperty("_WelcomMessage");
    }

    public String getSubDomainWelcomeMessageHeader() {
        return this.getSubdomainSpecificProperty("_WelcomMessageHeader");
    }

    public String getSubDomainWelcomeImage() {
        return staticContentURL + SUBDOMAIN_IMAGES_SUFFIX + SUBDOMAIN_WELCOME_IMAGES_SUFFIX
                + this.getSubdomainSpecificProperty("_WelcomeImage");
    }

    public String getSubDomainLogo() {
        String imageName = this.getSubdomainSpecificProperty("_Logo");
        if (StringUtils.isNotEmpty(imageName)) {
            return staticContentURL + SUBDOMAIN_IMAGES_SUFFIX + SUBDOMAIN_LOGOS_SUFFIX + imageName;
        }
        else {
            return "";
        }
    }

    public String getCustomerServiceInfo() {
        return this.getSubdomainSpecificProperty("_customerServiceInfo");
    }

    public String getCallUsPhone() {
        return this.getSubdomainSpecificProperty("_callUsPhone");
    }

    public String getCallUsDays() {
        return this.getSubdomainSpecificProperty("_callUsDays");
    }

    public String getCallUsHrs() {
        return this.getSubdomainSpecificProperty("_callUsHrs");
    }

    public String getEmailUsAddress() {
        return this.getSubdomainSpecificProperty("_emailUsAddress");
    }

    public String getVisitUsSite() {
        return this.getSubdomainSpecificProperty("_visitUsSite");
    }

    public String getVisitUsSiteToDisplay() {
        return this.getSubdomainSpecificProperty("_visitUsSiteToDsiplay");
    }

    public String getFaceBook() {
        return this.getSubdomainSpecificProperty("_facebook");
    }

    public String getLinkedIn() {
        return this.getSubdomainSpecificProperty("_linkedin");
    }

    public String getYouTube() {
        return this.getSubdomainSpecificProperty("_youtube");
    }

    public String getWordPress() {
        return this.getSubdomainSpecificProperty("_wordpress");
    }

    public String getCopyRight() {
        return this.getSubdomainSpecificProperty("_copyright");
    }

    public String getAboutUsUrl() {
        return this.getSubdomainSpecificProperty("_aboutUsUrl");
    }

    public String getContactUsUrl() {
        return this.getSubdomainSpecificProperty("_contactUsUrl");
    }

    public String getReturnPolicyUrl() {
        return this.getSubdomainSpecificProperty("_returnPolicyUrl");
    }

    public String getTermsOfUseUrl() {
        return this.getSubdomainSpecificProperty("_termsOfUseUrl");
    }

    public String getSecurityUrl() {
        return this.getSubdomainSpecificProperty("_securityUrl");
    }

    public String getPrivacyUrl() {
        return this.getSubdomainSpecificProperty("_privacyUrl");
    }

    public String getPrivacyEmail() {
        return tenantProperties.getProperty("privacy_page_email_address");
    }

    public String getCreateUserRequestInstructions() {
        return this.getSubdomainSpecificProperty("_createUserRequest_instructions");
    }

    public String getShowTrustKeeperPopup() {
        return this.getSubdomainSpecificProperty("_showTrustKeeperPopup");
    }

    /**
     * Takes a property name, and returns the value of that property for the 
     * subdomain and tenant. Follows this logic:
     * 
     * If the tenant is APD, checks <subdomain>_<property_value>, then 
     * <generic_subdomain>_<property_value>. If the tenant isn't APD, checks
     * <tenantName>_<subdomain>_<property_value>, then 
     * <tenantName>_<generic_subdomain>_<property_value>, then
     * <generic_subdomain>_<property_value>.
     * 
     * @param propertyName
     * @return
     */
    private String getSubdomainSpecificProperty(String propertyName) {
        //sets the tenant name prefix for the values to fetch
        String tenantPrefix = tenantName + "_";
        //if the tenant is APD, sets the prefix to the empty string
        if (TenantConfigRepository.getInstance().getGenericTenantId().equals(
                TenantConfigRepository.getInstance().getTenantIdByName(tenantName))) {
            tenantPrefix = "";
        }
        //used to look up the tenant's subdomain-specific styling
        String subdomainKey = tenantPrefix + this.getSubdomainValue() + propertyName;
        //used to look up the tenant's generic styling
        String tenantKey = tenantPrefix + IpSubdomainRestriction.GENERIC_SUBDOMAIN + propertyName;
        //used to look up the site's generic styling 
        String genericKey = IpSubdomainRestriction.GENERIC_SUBDOMAIN + propertyName;
        if (themeMapProperties.containsKey(subdomainKey)) {
            return themeMapProperties.getProperty(subdomainKey, "");
        }
        else if (themeMapProperties.containsKey(tenantKey)) {
            return themeMapProperties.getProperty(tenantKey, "");
        }
        else {
            return themeMapProperties.getProperty(genericKey, "");
        }
    }

    public void validateEmailDomain(FacesContext context, UIComponent component, Object value) {
        if (value != null && !accountBp.validEmailAddress(value.toString(), getSubdomainValue())) {
            ((UIInput) component).setValid(false);
            FacesMessage message = new FacesMessage();
            message.setSeverity(FacesMessage.SEVERITY_ERROR);
            message.setSummary(TenantConfigRepository.getInstance().getProperty(tenantName, "ecommerce",
                    "registration.email.invalid.summary"));
            message.setDetail(TenantConfigRepository.getInstance().getProperty(tenantName, "ecommerce",
                    "registration.email.invalid.detail"));
            context.addMessage(null, message);
        }
    }
}

phoenix-shopping/src/main/java/com/apd/phoenix/shopping/view/jsf/bean/utils/LinksBean.java
package com.apd.phoenix.shopping.view.jsf.bean.utils;

import java.io.Serializable;
import java.net.InetAddress;
import javax.ejb.Stateless;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Named;

/**
 * This is a utility bean, used to generate URLs for the shopping site.
 * 
 * @author RHC
 *
 */
@Named
@Stateless
public class LinksBean implements Serializable {

    private static final String ECOMMERCE_PRODUCT_LOOKAHEAD_ENDPOINT = "/rest/typeahead/mainSearch/";
    private static final String ECOMMERCE_CARTRIDGE_LOOKAHEAD_ENDPOINT = "/rest/typeahead/cartridgeSearch/";
    private static final String ECOMMERCE_MODEL_LOOKAHEAD_ENDPOINT = "/rest/typeahead/modelSearch/";
    private static final String ECOMMERCE_SMART_SEARCH_LOOKAHEAD = "/rest/typeahead/smartSearch/";
    private static final String ECOMMERCE_SMART_SEARCH_CARTRIDGE_NUMBER_LOOKAHEAD = "/rest/typeahead/smartSearch/cartridge/";
    private static final String ECOMMERCE_SMART_SEARCH_MODEL_NUMBER_LOOKAHEAD = "/rest/typeahead/smartSearch/model/";
    private static final String PUBLIC_RESET_PASSWORD_PAGE = "/ecommerce/user/resetPassword.xhtml";
    private static final String RESET_PASSWORD_PAGE = "/ecommerce/account/resetPassword.xhtml";
    public static final String PASSWORD_EXPIRED_PAGE = "/ecommerce/account/passwordExpired.xhtml";
    private static final String MY_ACCOUNT_PAGE = "/ecommerce/account/manage.xhtml";
    private static final String ECOMMERCE_HOME_PAGE = "/ecommerce/home.xhtml";
    private static final String ECOMMERCE_CASHOUT = "/ecommerce/cashout/checkout.xhtml";
    private static final String ECOMMERCE_PUNCHOUT = "/ecommerce/marketplace/returnCart.xhtml";
    private static final String ECOMMERCE_BROWSE = "/ecommerce/product/browse.xhtml";
    private static final String ECOMMERCE_COMPARE = "/ecommerce/product/compare.xhtml";
    private static final String ECOMMERCE_INK_TONER = "/ecommerce/product/inkTonerSearch.xhtml";
    private static final String ECOMMERCE_CART = "/ecommerce/shoppingCart/cart.xhtml";
    private static final String ECOMMERCE_ORDER_HISTORY = "/ecommerce/order/orderHistory.xhtml";
    private static final String ECOMMERCE_USER_FAVORITES = "/ecommerce/product/favorites.xhtml";
    private static final String ECOMMERCE_NEW_PUNCHOUT = "/ecommerce/marketplace/welcome.xhtml";
    private static final String ECOMMERCE_COMPANY_FAVORITES = "/ecommerce/product/companyFavorites.xhtml";
    private static final String ECOMMERCE_RETURN_CART = "/ecommerce/marketplace/returnCart.xhtml";
    private static final long serialVersionUID = 1L;
    private static final String REQUEST_ITEM = "/ecommerce/product/requestItem.xhtml";
    private static final String ITEM_NOT_FOUND = "/ecommerce/errors/itemNotFound.xhtml";
    private static final String ECOMMERCE_PUNCHOUT_CONTINUE_SHOPPING = "/ecommerce/marketplace/punchoutWindow.xhtml";
    private static final String ECOMMERCE_PUNCHOUT_EDIT = "/ecommerce/marketplace/punchoutWindow.xhtml";
    public static final String PASSWORD_RESET_INFO_PAGE = "/ecommerce/user/passwordResetInfo.xhtml";
    public static final String PASSWORD_CHANGED_PAGE = "/ecommerce/user/passwordChangedConfirmation.xhtml";
    public static final String ECOMMERCE_TASK_LIST = "/ecommerce/task/taskList.xhtml";

    public String getPasswordChangedPage() {
        return url(PASSWORD_CHANGED_PAGE);
    }

    public String getPasswordResetInfoPage() {
        return url(PASSWORD_RESET_INFO_PAGE);
    }

    public String getResetPassword() {
        return url(RESET_PASSWORD_PAGE);
    }

    public String getPublicResetPassword() {
        return url(PUBLIC_RESET_PASSWORD_PAGE);
    }

    public String getMyAccount() {
        return url(MY_ACCOUNT_PAGE);
    }

    public String getHome() {
        return url(ECOMMERCE_HOME_PAGE);
    }

    public String getCashout() {
        return url(ECOMMERCE_CASHOUT);
    }

    public String getBrowse() {
        return url(ECOMMERCE_BROWSE);
    }

    public String getCompare() {
        return url(ECOMMERCE_COMPARE);
    }

    public String getCart() {
        return url(ECOMMERCE_CART);
    }

    public String getOrderHistory() {
        return url(ECOMMERCE_ORDER_HISTORY);
    }

    public String getUserFavorites() {
        return url(ECOMMERCE_USER_FAVORITES);
    }

    public String getCompanyFavorites() {
        return url(ECOMMERCE_COMPANY_FAVORITES);
    }

    public String getRequestItem() {
        return url(REQUEST_ITEM);
    }

    public String getItemNotFound() {
        return url(ITEM_NOT_FOUND);
    }

    public String getReturnCart() {
        return url(ECOMMERCE_RETURN_CART);
    }

    private String url(String pathEnding) {
        ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
        StringBuilder toReturn = new StringBuilder();
        toReturn.append(context.getRequestContextPath());
        toReturn.append(pathEnding);
        return toReturn.toString();
    }

    public String getPunchout() {
        return url(ECOMMERCE_PUNCHOUT);
    }

    public String getNewPunchout() {
        return url(ECOMMERCE_NEW_PUNCHOUT);
    }

    public String getPunchoutContinueShopping() {
        return url(ECOMMERCE_PUNCHOUT_CONTINUE_SHOPPING);
    }

    public String getPunchoutEditOrder() {
        return url(ECOMMERCE_PUNCHOUT_EDIT);
    }

    public String getLookahead() {
        return url(ECOMMERCE_PRODUCT_LOOKAHEAD_ENDPOINT);

    }

    public String getHostName() {
        String hostName = "";

        try {
            hostName = InetAddress.getLocalHost().getHostName();
        }
        catch (Exception exp) {

        }
        return hostName;
    }

    public String getSmartSearchLookahead() {
        return url(ECOMMERCE_SMART_SEARCH_LOOKAHEAD);
    }

    public String getSmartSearchCartridgeLookahead() {
        return url(ECOMMERCE_SMART_SEARCH_CARTRIDGE_NUMBER_LOOKAHEAD);
    }

    public String getInkTonerSearch() {
        return url(ECOMMERCE_INK_TONER);
    }

    public String getTaskList() {
        return url(ECOMMERCE_TASK_LIST);
    }

    public String getSmartSearchModelLookahead() {
        return url(ECOMMERCE_SMART_SEARCH_MODEL_NUMBER_LOOKAHEAD);
    }

    public String getCartridgeLookahead() {
        return url(ECOMMERCE_CARTRIDGE_LOOKAHEAD_ENDPOINT);
    }

    public String getSolrModelLookahead() {
        return url(ECOMMERCE_MODEL_LOOKAHEAD_ENDPOINT);
    }
}

phoenix-shopping/src/main/webapp/WEB-INF/templates/ecommerceConfirmationTemplate.xhtml
<!DOCTYPE html>

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                template="/WEB-INF/templates/main/ecommerceInternalPageTemplate.xhtml">

    <ui:define name="styles">
        
    </ui:define>

    <ui:define name="page_title">#{display['confirmation.title']}</ui:define>

    <ui:define name="page_body">
        <ui:include src="./topNavBar.xhtml" />
        <div id="top-container" class="container">
        	<c:if test="#{!loginBean.isPunchout()}">
            <ui:include src="./mainNavBar.xhtml" />
            </c:if>
            <ui:insert name="page_content"></ui:insert>
        </div>
        <h:form style="display:none" prependId="false">
            <h:inputHidden id="maximumErrorSeverity" value="#{facesContext.maximumSeverity.ordinal}"/>
        </h:form>
    </ui:define>    
    
</ui:composition>

phoenix-shopping/src/main/webapp/WEB-INF/templates/topNavBarNotLoggedIn.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsp/jstl/core"	
                xmlns:forgeview="http://jboss.org/forge/view"
                xmlns:rich="http://richfaces.org/rich"
                xmlns:a4j="http://richfaces.org/a4j">

		<script type="text/javascript">
			$(document).ready(function() {
				$( '#j_username' ).attr( 'placeholder', 'Enter Username' ).val('').focus().blur();
				$( '#j_password' ).attr( 'placeholder', 'Enter Password' ).val('').focus().blur();
			});
		</script>
        <div id="ip-hdr">
            
            <div id="header" class="navbar navbar-fluid container">
            	<div id="logo">
            		<h:panelGroup rendered="#{not loginBean.isMarfieldSubdomain}">
		            	<a href="#{linksBean.home}">
		            		<img src="#{propertiesBean.get('tenant','content.service.secure.tenant.domain')}/images/APD-logo.png" 
		            			class="shoppingMainLogo"/>
		            	</a>
	            	</h:panelGroup>
            	</div>
	        	<h:panelGroup rendered="#{not empty pageCssBean.subDomainLogo}" layout="block" styleClass="subDomainLogoWrapper">
                    <img src="#{pageCssBean.subDomainLogo}" />
                </h:panelGroup>
               	<form id="login_form" class="form-inline" method="post" action="j_security_check">
               		<fieldset>
               			<h:panelGroup rendered="#{not loginBean.requiresDirectAccess}">
               				<!-- For most use cases, the username and password form will be displayed,
               				with additional account options -->
               				<div class="row-fluid" id="login-fields-row">
	                            <div id="login-UsernameFld" class="span4">
	                                <h:inputText id="j_username" required="true" 
	                                     styleClass="#{not component.valid ? 'ui-input-invalid' : ''}"/>
	                            </div>
	                            <div id="login-PasswordFld" class="span4">
	                                <h:inputSecret id="j_password" required="true" 
	                                     styleClass="#{not component.valid ? 'ui-input-invalid' : ''}"/>
	                            </div>
	                            <div class="span4">
	                            	<h:commandButton id="loginSubmit" value="Log in" class="btn btnRed" />
	                            </div>
                            </div>
							<div class="row-fluid" id="login-validation-row">
								<h:panelGroup rendered="#{not empty errorLogin and errorLogin}">
                       				<b>*Login Error: Either UserName/Password is incorrect.</b>
                       			</h:panelGroup>
                       		</div>
               				<div class="row-fluid" id="login-options-row">
                                <h:selectBooleanCheckbox id="rememberChk" value="Remember Me"/>
                                <h:outputLabel id="rememberLbl" value="Remember Me" for="rememberChk"/>
                            	<h:panelGroup rendered="#{not loginBean.isResetPasswordLinkHidden(pageCssBean.subdomainValue)}">
                                	<a href="#{linksBean.publicResetPassword}">Forgot Password</a>
                                </h:panelGroup>
		                        <h:panelGroup rendered="#{not loginBean.requiresUserMaintenance and not loginBean.isNovantSubdomain and not loginBean.isRegistrationLinkHidden(pageCssBean.subdomainValue)}">
									<a href="#{loginBean.createUserUrl}">Register</a>
		                        </h:panelGroup>
		                        <h:panelGroup rendered="#{not loginBean.requiresUserMaintenance and loginBean.isMarfieldSubdomain}">
									<a href="#{propertiesBean.get('tenant','content.service.secure.tenant.domain')}/Marfield_UserGuide.pdf">User Guide</a>
		                        </h:panelGroup>
		                        <h:panelGroup rendered="#{loginBean.requiresUserMaintenance and not loginBean.isNovantSubdomain and not loginBean.isRegistrationLinkHidden(pageCssBean.subdomainValue)}">
									<a href="#userMaintenance" data-toggle="modal">User Maintenance</a>
		                        </h:panelGroup>
		                        <h:panelGroup rendered="#{not loginBean.requiresUserMaintenance and loginBean.isNovantSubdomain and not loginBean.isRegistrationLinkHidden(pageCssBean.subdomainValue)}">
		                            <a href="#{loginBean.novantRegistrationInfoPage}" class="btn btn-info" style="background:green;border-color: green;">Employee Discount Program</a>
		                        </h:panelGroup>
	                        </div>
               			</h:panelGroup>
               			<h:panelGroup rendered="#{loginBean.requiresDirectAccess}">
               				<!-- For "requires direct access", just a "shop now" button will be displayed -->
	                        <div id="loginShopNowBtn">
	                            <h:commandButton id="shopNowBtn" value="Shop Now" styleClass="btn btn-primary pull-right" />
	                        </div>
               			</h:panelGroup>
               		</fieldset>
               	</form>
            </div>
        </div>
        
        <!-- LOGIN MODALS BEGIN -->
        <!-- RESET PASSWORD MODAL -->
		<c:if test="#{not loginBean.requiresDirectAccess and not loginBean.isResetPasswordLinkHidden(pageCssBean.subdomainValue)}">
        	<div id="passwordReset" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <h:form id="modalForm1">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
						<h3 id="myModalLabel">Reset Password</h3>
					</div>
		            <div class="modal-body">
						<h:outputLabel value="Enter Username:" />
						<h:inputText value="#{loginBean.passResetUsername}" />
					</div>
		            <div class="modal-footer">
						<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
						<h:commandButton value="Submit" action="#{loginBean.resetPassword()}" styleClass="btn btn-primary">
							<f:ajax execute="@form" onevent="modalEventHandler"/>
						</h:commandButton>
					</div>
				</h:form>
            </div>
		</c:if>
		<!-- USER MAINTENANCE MODAL -->
		<c:if test="#{not loginBean.requiresDirectAccess and not loginBean.isRegistrationLinkHidden(pageCssBean.subdomainValue)}">
            <div id="userMaintenance" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            		<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
						<h3 id="myModalLabel">User Maintenance</h3>
					</div>
		            <div class="modal-body">
		            	<form action="#{loginBean.createUserUrl}">
		            		<button class="userMaintenanceBtns">Create User</button>
		            	</form>
		            	<form action="#{loginBean.addLocationUrl}">
		            		<button style="margin-top:-20px" class="userMaintenanceBtns">Add Location</button>
		            	</form>
		            	<form action="#{loginBean.changeUserUrl}">
		            		<button style="margin-top:20px" class="userMaintenanceBtns">Change/Remove User</button>
		            	</form>
		            	<form action="#{loginBean.changeLocationUrl}">
		            		<button style="margin-top:20px" class="userMaintenanceBtns">Change/Remove Location</button>
		            	</form>
		            	
					</div>
		            <div class="modal-footer">
						<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>						
					</div>                
            </div>
		</c:if>
		<!-- RECOMMENDED BROWSERS MODAL -->
		<div id="bestViewingExp" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
             <h:form id="modalForm2">
                 <div class="modal-header">
                     <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                     <h3 id="myModalLabel">Recommeded Browsers</h3>
                 </div>
                 <div class="modal-body">
                     <div>
                     <b>For the best shopping experience, please, use one of these recommend browsers:</b>
                     </div>
                     <div style="width: 130px;margin-top: 20px; float:left;margin-left: auto; margin-right: auto; text-align:center">
                         <img src="#{propertiesBean.get('tenant','content.service.secure.tenant.domain')}/images/Websites/IE.png" width="100px" height="100px"/>
                         #{display['login.ieVersion']}
                     </div>
                     <div style="width: 130px;margin-top: 20px; float:left;margin-left: auto; margin-right: auto; text-align:center">
                         <img src="#{propertiesBean.get('tenant','content.service.secure.tenant.domain')}/images/Websites/Chrome.png" width="100px" height="100px"/>
                         #{display['login.chromeVersion']}
                     </div>
                     <div style="width: 130px;margin-top: 20px; float:left;margin-left: auto; margin-right: auto; text-align:center">
                         <img src="#{propertiesBean.get('tenant','content.service.secure.tenant.domain')}/images/Websites/Firefox.png" width="100px" height="100px"/>
                         #{display['login.firefoxVersion']}
                     </div>
                     <div style="width: 130px;margin-top: 20px; float:left;margin-left: auto; margin-right: auto; text-align:center">
                         <img src="#{propertiesBean.get('tenant','content.service.secure.tenant.domain')}/images/Websites/Safari.png" width="100px" height="100px"/>
                         #{display['login.safariVersion']}
                     </div>
                 </div>
                 <div class="modal-footer">
                     <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                 </div>
             </h:form>
		</div>
		<!-- LOGIN MODALS END -->

</ui:composition>